spring:
  data:
    cassandra:
      request:
        consistency: local_one
        serial-consistency: local_serial
      contact-points: 172.20.0.5:9042,172.20.0.2:9042,172.20.0.3:9042
      local-datacenter: dc1
      connection:
        init-query-timeout: '1000'
      username: sfnvm
      password: teca@12#