application:
  title: DSE_INIT
  version: 1.0.0
spring:
  data:
    cassandra:
      request:
        consistency: local_one
        serial-consistency: local_serial
      contact-points: 10.64.112.23:9042
      local-datacenter: DC_Trans_Search
      connection:
        init-query-timeout: '1000'
        connect-timeout: 10s
      username: cassandra
      password: 88zMG7qxHvMS9AcDhspH
server:
  port: 8081
